#!/bin/bash

volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | tr -dc '0-9' | sed 's/^0\{1,2\}//' 2>&1)
vol="󰕾"


if [[ $volume -ge 100 ]]; then
    text="max"

elif [[ $volume -lt 10 ]]; then
    text="0$volume%"

else
    text="${volume}%"

fi


case "$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)" in
    *MUTED* ) mic="󰍭";;
    *) mic="󰍬";;
esac

case "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)" in
    *MUTED* )
     	vol="󰖁"
    ;;
esac

echo "$mic $vol $text"
