#!/bin/bash

data=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>&1)
volume=$(echo $data | tr -dc '0-9' | sed 's/^0\{1,2\}//' )


case "$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)" in
    *MUTED* ) mic="";;
    *) mic="󰍬 ";;
esac

case "$data" in
    *MUTED* ) vol="󰖁" ;;
    *) vol="󰕾" ;;
esac

echo "$mic$vol $volume%"
