#!/bin/bash

brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
percent=$(( "$brightness * 100 / $max_brightness" ))

echo " ${percent}%"
