#!/bin/bash


brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
percent=$(( "$brightness * 100 / $max_brightness" ))

if [[ ${percent} -lt 10 ]]; then
    echo " 0$percent%"

elif [[ ${percent} -eq 100 ]]; then
    echo " max"

else
    echo " ${percent}%"

fi
