#!/bin/sh


get_connection_icon() {
    nmcli -t -f TYPE,DEVICE connection show --active | while read -r line; do
        case "$line" in
            "802-3-ethernet"*)
                echo " "
                return
                ;;
            "802-11-wireless"*)
                echo "󱚽 "
                return
                ;;
            *)
                echo "󰅛 "
                return
                ;;
        esac
    done
    
}

get_connection_icon
