#!/bin/sh
data=$(nmcli -t -f TYPE,DEVICE connection show --active)

case "$data" in
    "802-3-ethernet"*) eth="󰈀 " ;;
    "802-11-wireless"*) eth="󱚽 " ;;
    *) eth="󰅛 " ;;
esac    

if echo "$data" | grep -q "wireguard"; then
    virt="!"
fi

echo "$virt$eth"
