#!/bin/sh

case $2 in 
    fine)
        step="1"
        ;;
    *)
        step="5"
        ;;
esac

case $1 in
	up)
		wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
		wpctl set-volume -l 1.2 @DEFAULT_AUDIO_SINK@ $step%+
		;;
	down)
		wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
		wpctl set-volume -l 1.2 @DEFAULT_AUDIO_SINK@ $step%-
		;;
	mute)
		wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
		;;
esac

VOLUME=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | tr -dc '0-9' | sed 's/^0\{1,2\}//')


send_notification() {
	if [ "$1" = "mute" ]; then
        TEXT="speaker muted";
    else
        TEXT="currently speaker at ${VOLUME}%";
    fi

	notify-send -a "volume" -r 9993 -h int:value:"$VOLUME" "$TEXT" -t 1500
}

pkill -RTMIN+1 dwmblocks
case $1 in
	mute)
		case "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)" in
			*MUTED* ) send_notification mute;;
			*       ) send_notification;;
		esac;;
	*)
		send_notification;;
esac
